<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 210%;text-align: center;border-radius: 10px 70px">
     SQLite -DATABASE

</center></p></h1>

In [1]:

import pandas as pd
import sqlite3

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 210%;text-align: center;border-radius: 10px 70px">
     *Data Analysis of AI CO2 PROCESSS Using SQL

</center></p></h1>

<div style="border-radius:5px; border:3px solid #008000; background:#F2FFFF; padding:10px; font-family:cursive; font-size:14px; color:black; text-align:justify;">

  <p style="font-weight:bold; color:green; font-size:15px;">Project Achievements: Database Integration & Python-SQL Workflow</p>
  <ul>
    <li>Established robust connection to relational database using <b>SQLAlchemy</b> for automated data extraction and storage.</li>
    <li>Implemented <b>ETL pipeline</b> with Python to read multi-sheet experimental datasets via <b>pandas pd.read_sql()</b>, perform preprocessing, and load cleaned data back to SQL tables.</li>
    <li>Designed SQL queries for flexible aggregation, filtering, and feature extraction directly from Python, enabling scalable data analysis and ML-ready datasets.</li>
    <li>Automated dataset refresh and preprocessing workflows to ensure reproducibility and seamless integration with <b>ensemble ML models</b>.</li>
    <li>Handled large-scale experimental data across multiple device types while maintaining data integrity, type consistency, and standardized categorical labels.</li>
  </ul>

</div>

In [ ]:
csv_file_path = "preprocessor_output.xlsx"
df = pd.read_excel(csv_file_path)
df.head()

,materials,Method,surface area (m2/g),total pore volume(cm3/g),micropore volume (cm3/g),Mixing Time (min),Flow Rate (L/min),pressure (bar),co2 uptake (mmol/g),Efficiency (%),temp (°c)
0,Be12(OH)12(BTB)4,Treatment,1281.6,0.71,0.320000,10,7.17,50,5.764,66.58,100
1,Be12(OH)12(BTB)4,No Treatment,1012.6,0.56,0.220000,10,8.83,70,3.639,75.87,80
2,Be12(OH)12(BTB)4,Treatment,1408.8,0.83,0.360000,30,8.93,75,7.117,83.22,80
3,Be12(OH)12(BTB)4,Treatment,1403.9,0.85,0.330000,60,2.04,60,4.902,78.24,100
4,Cd4(TCPM)2,No Treatment,841.3,0.36,0.516845,90,5.50,50,5.136,62.47,80

In [8]:
conn = sqlite3.connect("preprocessor_output.db")
df.to_sql("process_data", conn, if_exists="replace", index=False)  # creates the table

521

In [9]:
table_name = "process_data"
df = pd.read_sql(f"SELECT * FROM {table_name}", conn)
df.shape

(521, 11)

In [10]:
df = pd.read_sql_query("SELECT * FROM process_data", conn)
print("Data Extracted:")
df.head()

Data Extracted:

,materials,Method,surface area (m2/g),total pore volume(cm3/g),micropore volume (cm3/g),Mixing Time (min),Flow Rate (L/min),pressure (bar),co2 uptake (mmol/g),Efficiency (%),temp (°c)
0,Be12(OH)12(BTB)4,Treatment,1281.6,0.71,0.320000,10,7.17,50,5.764,66.58,100
1,Be12(OH)12(BTB)4,No Treatment,1012.6,0.56,0.220000,10,8.83,70,3.639,75.87,80
2,Be12(OH)12(BTB)4,Treatment,1408.8,0.83,0.360000,30,8.93,75,7.117,83.22,80
3,Be12(OH)12(BTB)4,Treatment,1403.9,0.85,0.330000,60,2.04,60,4.902,78.24,100
4,Cd4(TCPM)2,No Treatment,841.3,0.36,0.516845,90,5.50,50,5.136,62.47,80

In [7]:
query = '''
SELECT *
FROM process_data
LIMIT 5;
'''

result = pd.read_sql_query(query, conn)
result

,materials,Method,surface area (m2/g),total pore volume(cm3/g),micropore volume (cm3/g),Mixing Time (min),Flow Rate (L/min),Pressure (bar),co2 uptake (mmol/g),Efficiency (%)
0,Be12(OH)12(BTB)4,Treatment,1281.6,0.71,0.320000,10,7.17,50,5.764,66.58
1,Be12(OH)12(BTB)4,No Treatment,1012.6,0.56,0.220000,10,8.83,70,3.639,75.87
2,Be12(OH)12(BTB)4,Treatment,1408.8,0.83,0.360000,30,8.93,75,7.117,83.22
3,Be12(OH)12(BTB)4,Treatment,1403.9,0.85,0.330000,60,2.04,60,4.902,78.24
4,Cd4(TCPM)2,No Treatment,841.3,0.36,0.516845,90,5.50,50,5.136,62.47

In [9]:
#get all brances
query = '''
SELECT * 
FROM process_data
ORDER BY "co2 uptake (mmol/g)" DESC
LIMIT 10;
'''

result = pd.read_sql_query(query, conn)
result

,materials,Method,surface area (m2/g),total pore volume(cm3/g),micropore volume (cm3/g),Mixing Time (min),Flow Rate (L/min),Pressure (bar),co2 uptake (mmol/g),Efficiency (%)
0,NOTT-106,Treatment,217.0,0.12,0.130000,60,8.17,600,7.557,79.95
1,DUT-9,Treatment,2511.0,1.35,1.160000,60,1.47,750,7.383,86.92
2,IRMOF-11,Treatment,1005.4,0.41,0.340000,60,7.21,750,7.324,84.07
3,NOTT-101,Treatment,2700.0,1.33,0.516845,60,5.43,750,7.177,84.15
4,Be12(OH)12(BTB)4,Treatment,1408.8,0.83,0.360000,30,8.93,75,7.117,83.22
5,TMU-24,Treatment,2305.0,1.23,0.130000,60,9.71,500,7.029,70.08
6,Cd6(CPOM)3(H2O)6,Treatment,1813.0,1.05,0.700000,90,6.83,300,6.982,65.10
7,UiO-68-Ant,Treatment,1893.0,0.79,0.780000,20,6.70,750,6.855,83.62
8,Mg-MOF-74,Treatment,1684.0,1.43,0.480000,60,4.56,50,6.820,71.14
9,MOF-808,Treatment,660.0,0.28,0.240000,30,7.71,600,6.790,77.91

In [10]:
#Calculate total revenue per branch.
query = '''
SELECT 
    "pressure (bar)" as pressure, 
    "co2 uptake (mmol/g)" AS avg_eff
FROM process_data
GROUP BY pressure
ORDER BY pressure;
'''
result = pd.read_sql_query(query, conn)
result

    pressure  avg_eff
0         30    2.143
1         40    3.355
2         50    5.764
3         60    4.902
4         64    4.021
5         70    3.639
6         75    7.117
7         85    5.236
8         90    3.163
9        300    4.990
10       500    5.157
11       600    3.813
12       750    6.769

In [11]:
# =============================
#  SQLite Connection
# =============================
# SQLite database file
db_file = 'preprocessor_output.db'

# Connect
conn = sqlite3.connect(db_file)

# =============================
# Extract Data from SQL
# =============================
df = pd.read_sql_query("SELECT * FROM process_data", conn)
print("Data Extracted:")
df.head()

Data Extracted:

,materials,Method,surface area (m2/g),total pore volume(cm3/g),micropore volume (cm3/g),Mixing Time (min),Flow Rate (L/min),Pressure (bar),co2 uptake (mmol/g),Efficiency (%)
0,Be12(OH)12(BTB)4,Treatment,1281.6,0.71,0.320000,10,7.17,50,5.764,66.58
1,Be12(OH)12(BTB)4,No Treatment,1012.6,0.56,0.220000,10,8.83,70,3.639,75.87
2,Be12(OH)12(BTB)4,Treatment,1408.8,0.83,0.360000,30,8.93,75,7.117,83.22
3,Be12(OH)12(BTB)4,Treatment,1403.9,0.85,0.330000,60,2.04,60,4.902,78.24
4,Cd4(TCPM)2,No Treatment,841.3,0.36,0.516845,90,5.50,50,5.136,62.47